Standardized/modularized queues
USGS-Astrogeology/PDS-Pipelines pull request #527
Opened 2021-01-20 02:34 UTC by AustinSanders

First pass at standardizing / modularizing queues.  Needs testing and minor reworks.

The first pass includes an attempt at establishing an interface for queueing processes.  Since it was reverse-engineered, it's somewhat of a loose-fitting interface at the moment.  I'd like to see if/how we can polish it.

The QueueProcess class serves as a base process model, and it stores all the information necessary to get the queueing processes up and running (archive, volume, search string information, a session maker, etc.).  Each of the child classes is responsible for providing a "get_matching_files" and "enqueue" implementation, and that seems to be enough to get things moving along.

I wasn't sure about storing the session maker and Redis connections within the objects, but I decided to allow the object to self-manage / maintain its connections because they are required for proper queueing operation, i.e. it doesn't ever make sense to have a QueueProcess that doesn't have a database connection or Redis connection (since we're grabbing items from the database and pushing them to a Redis queue).

Things I need to do before this is ready for review / merge:
- [ ] A full run of DI processing
- [ ] A full run of UPC processing
- [ ] A full run of derived processing
- [ ] Additional docstrings
- [ ] Removal of unused imports

2021-01-20 16:21 UTC, dpmayerUSGS commented on pds_pipelines/queueing.py
> +    def __init__(self, process_name, archive, volume=None, search=None, log_level='INFO'):
@AustinSanders Could we also add queue namespace as a parameter? We currently allow overriding the default namespace on the commandline in `service_job_manager.py`.

2021-01-20 22:36 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +    def enqueue(self, element, copy):
One thing that I'm not particularly happy with is the enqueue function.  Specifically, it seem to break the single responsibility principle in that it is responsible for both copying and queueing.  I wasn't able to find an elegant way of splitting up the functionality since the the filename that we're queueing comes from the copy function rather than the query object.  I don't think this would be too hard to fix, but I'm blanking.

2021-01-20 22:36 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +        if copy:
I don't know of any scenario in which we'd want to copy the files for DI processing, but the copy flag was necessary in order to make this fit the interface.  I think this is the natural consequence of deriving an interface from existing components rather than starting with a clean interface design upon which components are built.  I don't think this is _too_ big of an issue, but it's worth pointing out.

2021-01-20 22:36 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +        self.process_name = process_name
I didn't put too much though into which of these should be member variables and which should be passed around the object.  Since this is an object that represents a process, I kind of just stuffed everything process-related in here.  Might be worth trimming down?

2021-01-20 22:36 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +        self.session_maker = pds_session_maker
I could use a second opinion on this.  I decided to let the object manage its own sessions (rather than creating a session / sessionmaker and passing it to the object) because, no matter what, the queueing process requires a database connection.  Since queues are essentially pulling from the database and putting into redis queues, it made sense to me to allow the object to manage its own database / redis connections.

2021-01-20 22:57 UTC, dpmayerUSGS commented on pds_pipelines/queueing.py
> +        if copy:
DI is purely about checking that the checksum in the database matches the checksum of the file *in the exact location* recorded in the database, so we would never need to copy the file as part of running DI.
That being said, I don't think there's an issue with the solution here.

2021-01-20 23:00 UTC, dpmayerUSGS commented
@AustinSanders I think `ingest_queueing.py` needs to be updated (and tested) as well.

2021-01-21 18:25 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +        if copy:
I resolved this with **kwargs.  There's still a flexible interface for enqueue, but it allows additional keyword arguments as needed.

2021-01-21 21:52 UTC, acpaquette reviewed
Overall looks good! A couple questions and potential changes, dig the polymorphism to reduce redundant code!

2021-01-21 21:52 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        return logger
Could be changed to a has attribute model, something like:
```
if not (hasattr(self, logger)):
    ~get the logger~
    self.logger = logger
return self.logger
```

2021-01-21 21:52 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        self.process_queue = RedisQueue(f"{process_name}_ReadyQueue", namespace)
I don't think process queue is necessarily wrong here but it's a bit of a misnomer, maybe `ready_queue` instead?

2021-01-21 21:52 UTC, acpaquette commented on pds_pipelines/queueing.py
> +    def enqueue(self, element, **kwargs):
kwargs isn't being used here. Is this just a signature thing or do the kwargs need to be pushed to the queue?

2021-01-21 21:52 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        # Default to empty string if falsy value specified
falsy to false

2021-01-21 21:55 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        self.session_maker = pds_session_maker
I think this is fine. These problems tend to happen a fair amount when using an object oriented approach but I don't think it's out of the objects scope to query the DB since it needs it to build the set of items to send to the queue

2021-01-21 21:59 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        self.process_name = process_name
I don't know if these objects necessarily represent a process, rather they build sets that represent processes. It more or less needs the process_name, archive, we could have setters for the rest but they could also remain as they are. It's more of a personal preference and really depends on the person programming it. I think this is great for a first pass and we can change things if we want to down the line

2021-01-21 22:03 UTC, acpaquette commented on pds_pipelines/queueing.py
> +    def enqueue(self, element, copy):
Was this fixed/addressed? It looks like there are some leftover lines of code that could be changed. The actual copy looks like it could be taken care of in the run function on the base object?

2021-01-21 23:19 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +    def enqueue(self, element, **kwargs):
This is just a signature thing in order to allow the enqueue(element, copy=copy) in the run loop.  It's kind of ugly, but I wasn't sure how else to handle scenarios in which _some_ queue types require a copy flag.

2021-01-21 23:19 UTC, AustinSanders commented on pds_pipelines/queueing.py
> +        # Default to empty string if falsy value specified
As much as I hate it, "falsy" is a thing, and I feel that it's more applicable here. [reference](https://stackoverflow.com/questions/39983695/what-is-truthy-and-falsy-how-is-it-different-from-true-and-false)

2021-01-22 20:17 UTC, acpaquette approved these changes
One small thing to fix but other than that this looks solid!

2021-01-22 20:17 UTC, acpaquette commented on pds_pipelines/available_modules.py
> +    from osgeo import gdal
I swear I have fixed this like two or three times now 😢 I would also update the ogr import

2021-01-22 20:19 UTC, acpaquette commented on pds_pipelines/queueing.py
> +        self.logger = self.get_logger(log_level)
Technically this doesn't have to be set like this any more but it can also stay this way

2021-01-22 20:37 UTC, dpmayerUSGS requested changes
Once you update the gdal import in available_modules, this PR will be good to merge.

2021-01-22 20:37 UTC, dpmayerUSGS commented on pds_pipelines/available_modules.py
> +    from osgeo import gdal
@AustinSanders IMO this is the only thing standing in the way of merging at this point

2021-01-23 01:22 UTC, dpmayerUSGS approved these changes

2021-01-23 02:30 UTC, merged

2021-01-23 02:31 UTC, dpmayerUSGS commented
Closes #469